name: Default (push)

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

env:
  DOCKSAL_VERSION: develop
  # Setting these while testing locally may result in data loss, so only use in CI.
  DOCKSAL_DNS_DISABLED: 1
  DOCKSAL_DNS_DOMAIN: docksal.site
  EVENT_NAME: '${{ github.event_name }}'
  REPO: docksal/varnish

jobs:
  default:
    name: 'Build, test, and push'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          -
            version: '6.0'
            tags: '6.0'
          -
            version: '6.2'
            tags: '6.2,latest'

    env:
      VERSION: ${{ matrix.version }}
      TAGS: ${{ matrix.tags }}

    steps:
      -
        name: Source name
        id: source_name
        run: |
          echo "::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}"
          echo "::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}"
          if [[ ${{ github.event.ref }} =~ ^refs/tags/ ]]; then
              echo "::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}"
          else
              echo "::set-output name=SOURCE_TAG::"
          fi
      -
        name: Install BATS (tests)
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
          bats -v
      -
        # Hack to fix docker-gen in Github Actions
        # Drops docker daemon config with custom cgroup (which docker-gen does not support)
        # See https://github.com/jwilder/docker-gen/issues/315
        name: Fix docker-gen in Github Actions
        run: |
          sudo rm /etc/docker/daemon.json
          sudo service docker restart
      -
        name: Install Docksal
        run: curl -sSL http://get.docksal.io | bash
      -
        name: fin version
        run: fin version
      -
        name: fin sysinfo
        run: fin sysinfo
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and test
        run: |
          make
          make start
          make test
      -
        name: Release on success
        if: |
          success() &&
          (
            github.ref == 'refs/heads/develop' ||
            github.ref == 'refs/heads/master' ||
            startsWith(github.ref, 'refs/tags')
          )
        run: ./release.sh
        env:
          SOURCE_NAME: '${{ steps.source_name.outputs.SOURCE_NAME }}'
          SOURCE_BRANCH: '${{ steps.source_name.outputs.SOURCE_BRANCH }}'
          SOURCE_TAG: '${{ steps.source_name.outputs.SOURCE_TAG }}'
      -
        name: Log on failure
        if: ${{ failure() }}
        run: make logs
